import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata = {
  title: ".::Meta blog::.",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "SatoruGojo",
        height: 1920,
        width: 1080,
        alt: "",
      },
    ],
  },
};

const workSans = Work_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${workSans.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
